### ISSUE TITLE
long running on real drives fail due to OOM in add chunk after some time

### ISSUE THREAD

**Issue by shosseinimotlagh** [eBay/HomeStore#492]
`python3 /usr/local/bin/scripts/long_running.py --test_suits=index_long_running --dirpath=/usr/local/bin/ --dev_list=/dev/index,/dev/data1,/dev/data2,/dev/data3`

[08/08/24 17:29:33-07:00] [I] [91] [homestore_test_common.hpp:361:do_start_homestore] Taking input dev_list: /dev/index,/dev/data1,/dev/data2,/dev/data3
[08/08/24 17:29:33-07:00] [I] [91] [homestore_test_common.hpp:486:init_raw_devices] Successfully zeroed the 1st 4194304 bytes of device /dev/index
[08/08/24 17:29:33-07:00] [I] [91] [homestore_test_common.hpp:486:init_raw_devices] Successfully zeroed the 1st 4194304 bytes of device /dev/data1
[08/08/24 17:29:33-07:00] [I] [91] [homestore_test_common.hpp:486:init_raw_devices] Successfully zeroed the 1st 4194304 bytes of device /dev/data2
[08/08/24 17:29:33-07:00] [I] [91] [homestore_test_common.hpp:486:init_raw_devices] Successfully zeroed the 1st 4194304 bytes of device /dev/data3
[08/08/24 17:29:33-07:00] [I] [91] [homestore_test_common.hpp:389:do_start_homestore] Starting iomgr with 2 threads, spdk: false
[08/08/24 17:29:33-07:00] [I] [91] [iomgr_config.hpp:48:operator()] Default Pools is not initialized, possibly first boot - setting with defaults
[08/08/24 17:29:33-07:00] [I] [91] [iomgr.cpp:111:start] Starting IOManager version 0.0.0+unknown with 2 threads [is_spdk=false] [mem_limit=512mb, hugepage=0]
[08/08/24 17:29:33-07:00] [I] [94] [reactor.hpp:50:IOThreadMetrics] Registring metrics group name = IOThreadMetrics, thread_name = iomgr_thread_0
[08/08/24 17:29:33-07:00] [I] [95] [reactor.hpp:50:IOThreadMetrics] Registring metrics group name = IOThreadMetrics, thread_name = iomgr_thread_1
[08/08/24 17:29:33-07:00] [I] [94] [iomgr_timer.cpp:179:setup_timer_fd] Creating non-recurring per-thread timer fd 7 and adding it into fd poll list
[08/08/24 17:29:33-07:00] [I] [95] [iomgr_timer.cpp:179:setup_timer_fd] Creating non-recurring per-thread timer fd 12 and adding it into fd poll list
[08/08/24 17:29:33-07:00] [I] [95] [iomgr.cpp:347:reactor_started] All Worker reactors started, moving iomanager to sys_init state
[08/08/24 17:29:33-07:00] [I] [91] [iomgr_timer.cpp:179:setup_timer_fd] Creating non-recurring global timer fd 15 and adding it into fd poll list
[08/08/24 17:29:33-07:00] [I] [91] [iomgr_timer.cpp:179:setup_timer_fd] Creating non-recurring global timer fd 16 and adding it into fd poll list
[08/08/24 17:29:33-07:00] [I] [91] [iomgr.cpp:172:start] IOManager is ready and move to running state
[08/08/24 17:29:33-07:00] [I] [91] [homestore_test_common.hpp:80:generate_random_http_port] random port generated = 66528
[08/08/24 17:29:33-07:00] [I] [91] [homestore_test_common.hpp:71:set_fixed_http_port] http port = 66528
[08/08/24 17:29:33-07:00] [I] [91] [homestore_test_common.hpp:400:do_start_homestore] Initialize and start HomeStore with app_mem_size = 460.80mb
[08/08/24 17:29:33-07:00] [I] [91] [homestore_config.hpp:93:operator()] Free Blks Slab distribution is not initialized, possibly first boot - setting with defaults
[08/08/24 17:29:33-07:00] [I] [91] [homestore_config.hpp:105:init_settings_default] Some settings are defaultted or overridden explicitly in the code, saving the new settings
[08/08/24 17:29:33-07:00] [I] [91] [homestore.cpp:137:start] Homestore is loading with following services: meta,index,
[08/08/24 17:29:33-07:00] [I] [91] [cp_mgr.cpp:363:CPWatchdog] CP watchdog timer setting to : 10 seconds
[08/08/24 17:29:33-07:00] [I] [91] [iomgr_timer.cpp:179:setup_timer_fd] Creating recurring global timer fd 22 and adding it into fd poll list
[08/08/24 17:29:33-07:00] [I] [134] [reactor.hpp:50:IOThreadMetrics] Registring metrics group name = IOThreadMetrics, thread_name = cp_io
[08/08/24 17:29:33-07:00] [I] [134] [iomgr_timer.cpp:179:setup_timer_fd] Creating non-recurring per-thread timer fd 25 and adding it into fd poll list
[08/08/24 17:29:33-07:00] [I] [91] [drive_interface.cpp:220:get_drive_type] Drive=/dev/index is detected to be drive_type=block_nvme
[08/08/24 17:29:33-07:00] [I] [91] [drive_interface.cpp:220:get_drive_type] Drive=/dev/data1 is detected to be drive_type=block_hdd
[08/08/24 17:29:33-07:00] [I] [91] [device_manager.cpp:78:DeviceManager] Overridding HDD open flags from DIRECT_IO to BUFFERED_IO
[08/08/24 17:29:33-07:00] [I] [91] [drive_interface.cpp:220:get_drive_type] Drive=/dev/data2 is detected to be drive_type=block_hdd
[08/08/24 17:29:33-07:00] [I] [91] [drive_interface.cpp:220:get_drive_type] Drive=/dev/data3 is detected to be drive_type=block_hdd
[08/08/24 17:29:33-07:00] [I] [91] [physical_dev.cpp:87:PhysicalDev] Opening device /dev/index with DIRECT_IO mode.
[08/08/24 17:29:33-07:00] [I] [91] [physical_dev.cpp:108:PhysicalDev] Device /dev/index opened with dev_id=28 size=465.75gb
[08/08/24 17:29:33-07:00] [I] [91] [device_manager.cpp:126:format_devices] Formatting Homestore on Device=/dev/index with first block as: [magic=0xceeddeeb, checksum=2049243141, first_blk_header=[gen_number=1, version=4, product_name=OmStore system_uuid=49a8bfed-2f9b-41be-8ee4-2b4494c6a832], this_pdev_info=[data_offset=8.79mb, size=465.74gb, pdev_id=0 max_pdev_chunks=14905 dev_attr=[phys_page_size=4kb, align_size=512, atomic_phys_page_size=4kb, num_streams=1] mirror_super_block?=false]] total_super_blk_size=8163840
[08/08/24 17:29:33-07:00] [I] [91] [physical_dev.cpp:87:PhysicalDev] Opening device /dev/data1 with BUFFERED_IO mode.
[08/08/24 17:29:33-07:00] [I] [91] [physical_dev.cpp:108:PhysicalDev] Device /dev/data1 opened with dev_id=29 size=5.46tb
[08/08/24 17:29:33-07:00] [I] [91] [device_manager.cpp:126:format_devices] Formatting Homestore on Device=/dev/data1 with first block as: [magic=0xceeddeeb, checksum=2793605628, first_blk_header=[gen_number=1, version=4, product_name=OmStore system_uuid=49a8bfed-2f9b-41be-8ee4-2b4494c6a832], this_pdev_info=[data_offset=183.19mb, size=5.46tb, pdev_id=1 max_pdev_chunks=357664 dev_attr=[phys_page_size=4kb, align_size=512, atomic_phys_page_size=4kb, num_streams=1] mirror_super_block?=true]] total_super_blk_size=183697408
[08/08/24 17:29:33-07:00] [I] [91] [physical_dev.cpp:87:PhysicalDev] Opening device /dev/data2 with BUFFERED_IO mode.
[08/08/24 17:29:33-07:00] [I] [91] [physical_dev.cpp:108:PhysicalDev] Device /dev/data2 opened with dev_id=30 size=5.46tb
[08/08/24 17:29:33-07:00] [I] [91] [device_manager.cpp:126:format_devices] Formatting Homestore on Device=/dev/data2 with first block as: [magic=0xceeddeeb, checksum=4164116312, first_blk_header=[gen_number=1, version=4, product_name=OmStore system_uuid=49a8bfed-2f9b-41be-8ee4-2b4494c6a832], this_pdev_info=[data_offset=183.19mb, size=5.46tb, pdev_id=2 max_pdev_chunks=357664 dev_attr=[phys_page_size=4kb, align_size=512, atomic_phys_page_size=4kb, num_streams=1] mirror_super_block?=true]] total_super_blk_size=183697408
[08/08/24 17:29:34-07:00] [I] [91] [physical_dev.cpp:87:PhysicalDev] Opening device /dev/data3 with BUFFERED_IO mode.
[08/08/24 17:29:34-07:00] [I] [91] [physical_dev.cpp:108:PhysicalDev] Device /dev/data3 opened with dev_id=31 size=5.46tb
[08/08/24 17:29:34-07:00] [I] [91] [device_manager.cpp:126:format_devices] Formatting Homestore on Device=/dev/data3 with first block as: [magic=0xceeddeeb, checksum=836999593, first_blk_header=[gen_number=1, version=4, product_name=OmStore system_uuid=49a8bfed-2f9b-41be-8ee4-2b4494c6a832], this_pdev_info=[data_offset=183.19mb, size=5.46tb, pdev_id=3 max_pdev_chunks=357664 dev_attr=[phys_page_size=4kb, align_size=512, atomic_phys_page_size=4kb, num_streams=1] mirror_super_block?=true]] total_super_blk_size=183697408
[08/08/24 17:29:34-07:00] [I] [91] [device_manager.cpp:251:create_vdev] meta Virtual device is attempted to be created with num_chunks=1, it needs to be adjust to new_num_chunks=12
[08/08/24 17:29:34-07:00] [I] [91] [device_manager.cpp:314:create_vdev] New Virtal Dev=meta of size=46.57gb with id=0 is attempted to be created with multi_pdev_opts=ALL_PDEV_STRIPED. The params are adjusted as follows: VDev_Size=46.57gb Num_pdevs=1 Total_chunks_across_all_pdevs=12 Each_Chunk_Size=3.88gb
[08/08/24 17:29:34-07:00] [I] [91] [device_manager.cpp:336:create_vdev] total size of type Fast in this homestore is  500088139264
[08/08/24 17:29:34-07:00] [I] [91] [device_manager.cpp:352:create_vdev] 12 chunks is created on pdev /dev/index for vdev meta, pdev data size is 500088139264
[08/08/24 17:29:34-07:00] [I] [91] [device_manager.cpp:373:create_vdev] 12 chunks is created for vdev meta, expected 12
[08/08/24 17:29:34-07:00] [I] [91] [device_manager.cpp:385:create_vdev] Virtal Dev=meta of size=46.57gb successfully created
[08/08/24 17:29:34-07:00] [I] [91] [device_manager.cpp:251:create_vdev] index Virtual device is attempted to be created with num_chunks=3, it needs to be adjust to new_num_chunks=2.87kb
[08/08/24 17:29:34-07:00] [I] [91] [device_manager.cpp:259:create_vdev] index Virtual device is attempted to be created with size=12600466227200, it needs to be rounded to new_size=12600460615680 to be the multiple of 11.46mb (num_chunks 2934 * blk_size 4kb).
[08/08/24 17:29:34-07:00] [I] [91] [device_manager.cpp:314:create_vdev] New Virtal Dev=index of size=11.46tb with id=1 is attempted to be created with multi_pdev_opts=ALL_PDEV_STRIPED. The params are adjusted as follows: VDev_Size=11.46tb Num_pdevs=3 Total_chunks_across_all_pdevs=2934 Each_Chunk_Size=4.00gb
[08/08/24 17:29:34-07:00] [I] [91] [device_manager.cpp:336:create_vdev] total size of type Data in this homestore is  18000666034176
[08/08/24 17:29:34-07:00] [I] [91] [device_manager.cpp:352:create_vdev] 978 chunks is created on pdev /dev/data1 for vdev index, pdev data size is 6000222011392
[08/08/24 17:29:34-07:00] [I] [91] [fixed_blk_allocator.cpp:25:FixedBlkAllocator] FixedBlkAllocator total blks: 1048495
[08/08/24 17:29:34-07:00] [I] [91] [fixed_blk_allocator.cpp:25:FixedBlkAllocator] FixedBlkAllocator total blks: 1048495
......
......
[08/08/24 17:40:10-07:00] [I] [91] [device_manager.cpp:352:create_vdev] 978 chunks is created on pdev /dev/data2 for vdev index, pdev data size is 6000222011392
.........
[08/08/24 17:50:38-07:00] [I] [91] [fixed_blk_allocator.cpp:25:FixedBlkAllocator] FixedBlkAllocator total blks: 1048495
[08/08/24 17:50:39-07:00] [I] [91] [fixed_blk_allocator.cpp:25:FixedBlkAllocator] FixedBlkAllocator total blks: 1048495
Killed
Test failed: Command '/usr/local/bin/test_index_btree --gtest_filter=BtreeConcurrentTest/0.ConcurrentAllOps --gtest_break_on_failure --cleanup_after_shutdown=False --init_device=True  --preload_size=262144  --run_time=14400 --num_iters=100000000 --num_entries=2097152 --num_threads=2 --num_fibers=2  --device_list=/dev/index,/dev/data1,/dev/data2,/dev/data3 ' returned non-zero exit status 137.
Traceback (most recent call last):
  File "/usr/local/bin/scripts/index_test.py", line 17, in run_test
    subprocess.check_call(f"{options['dirpath']}test_index_btree {cmd_opts}", stderr=subprocess.STDOUT, shell=True)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/usr/local/bin/test_index_btree --gtest_filter=BtreeConcurrentTest/0.ConcurrentAllOps --gtest_break_on_failure --cleanup_after_shutdown=False --init_device=True  --preload_size=262144  --run_time=14400 --num_iters=100000000 --num_entries=2097152 --num_threads=2 --num_fibers=2  --device_list=/dev/index,/dev/data1,/dev/data2,/dev/data3 ' returned non-zero exit status

**Comment by xiaoxichen** [comment]
@shosseinimotlagh pls verify and close this issue if resolved.
