### ISSUE TITLE
LogStore-Epoll hung

### ISSUE THREAD

**Issue by shosseinimotlagh** [eBay/HomeStore#540]
```
bt
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x58a60dddb590)
   at ./nptl/./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (cancel=true, private=0, abstime=0x0, clockid=0, expected=0, futex_word=0x58a60dddb590)
   at ./nptl/./nptl/futex-internal.c:87
#2  __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x58a60dddb590, expected=expected@entry=0, clockid=clockid@entry=0,
   abstime=abstime@entry=0x0, private=private@entry=0) at ./nptl/./nptl/futex-internal.c:139
#3  0x000074dd66d9aa41 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x58a60dddb540, cond=0x58a60dddb568)
   at ./nptl/./nptl/pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x58a60dddb568, mutex=0x58a60dddb540) at ./nptl/./nptl/pthread_cond_wait.c:627
#5  0x000058a609ea9877 in std::condition_variable::wait<LogStoreTest::wait_for_inserts()::{lambda()#1}>(std::unique_lock<std::mutex>&, LogStoreTest::wait_for_inserts()::{lambda()#1}) (this=0x58a60dddb568, __lock=@0x7fff50981240: {_M_device = 0x58a60dddb540, _M_owns = true},
     __p={__this = 0x58a60dddb520}) at /usr/include/c++/11/condition_variable:103
#6  0x000058a609e8ab49 in LogStoreTest::wait_for_inserts (this=0x58a60dddb520)
   at /tmp/source/source/forks/HomeStore/src/tests/test_log_store.cpp:612
#7  0x000058a609e51345 in LogStoreTest_VarRateInsertThenTruncate_Test::TestBody (this=0x58a60dddb520)
```

**Comment by JacksonYao287** [comment]
not a issue, this UT will take a little more time to complete
